name: Lint with ESLint

on:
  push:
    branches:
      - '**' # Run on pushes to all branches
  pull_request:
    branches:
      - '**' # Run on pull request to/from all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.10.0'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint ./client # Lint all files in the repository
